#!/bin/sh

# pkgdist.sh: converts .pkg files to distribution sets
#
# usage: ./pkgdist.sh [<option>]
#
# <option> is any of:
# 	- a pkg file
# 	    - all dependencies should be in the same location
# 	    - can be local, http://, https://, or ftp://
#   - 'src'
#   - 'tests'
#   - 'ports'
#   - 'base'
#   - 'base-dbg'
#   - 'kernel'
#   - 'kernels-dbg'
#   - 'minimal'
#   - 'minimal-dbg'
#
#   For all options except the pkg file, the distribution set will be created
#   from the corresponding package installed on the system.

if [ -z "$1" ]; then
	echo "Expected 1 or more arguments, got 0" >&2
	exit 1;
fi

tar_xz="tar -cvJf"

set -eu
temp=""
trap 'rm -rf "${temp}"' EXIT

get_files() {
	temp="$1"; shift
	package="$1"; shift
	pkglist="$1"; shift
	skip_first="$1"

	for dep in $(pkg info -dq "${package}*"); do
		for old_dep in ${pkglist}; do
			if [ "${old_dep}" = "${dep}" ]; then
				continue 2
			fi
		done
		pkglist="${pkglist} ${dep}"
		get_files "${temp}" "${dep}" "${pkglist}" ""
	done
	if [ -z "${skip_first}" ]; then
		pkg list "${package}" >> "${temp}"
	fi
}

for input_name in "$@"; do
	case ${input_name} in
		src|lib32|base-dbg|kernels-dbg|minimal|minimal-dbg|ports|base)
			temp=$(mktemp) || exit 1
			get_files "${temp}" "FreeBSD-set-${input_name}" "" ""
			${tar_xz} "${input_name}.txz" -nLT "${temp}"
			;;

		kernel)
			kern=$(pkg info -x FreeBSD-kernel | head -n 1)
			echo Making dist set from "${kern}"
			temp=$(mktemp) || exit 1
			get_files "${temp}" "${kern}" "" ""
			${tar_xz} kernel.txz -T "${temp}"
			;;

		*) # install the pkg to a temp folder and package that.
			temp=$(mktemp -d) || exit 1
			echo "${temp}"

			prefix=$(pwd)
			case "${input_name}" in
				"https://"*|"http://"*|"ftp://"*)
					prefix=""
					;;
				*)
					prefix="$(pwd)/"
					;;
			esac

			INSTALL_AS_USER=true ASSUME_ALWAYS_YES=true PKG_DBDIR="temp_pkgdb" pkg -r "${temp}" add "${prefix}${input_name}"
			
			# remove files generated by pkg
			rm -r "${temp}/temp_pkgdb"

			# make tarball
			output="${input_name%pkg}txz"
			${tar_xz} "${output}" -C "${temp}" .
			mv "${output}" .
			;;
	esac
done
